# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
        
    - name: test
      run: |
        npm install jasmine-node -g
        cd UnitTesting
        echo $PWD
        jasmine-node spec/
    - name: deploy 
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git push https://heroku:${{ secrets.HEROKU_TOKEN }}@git.heroku.com/lit-headland-82372.git origin/master:master
        echo "SUCCESS!!!!"
      env:
        CI: true
